global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'server-lion@qq.com'
    from: 'server-lion@qq.com'
    smarthost: 'smtp.qq.com:587'
    auth_username: 'server-lion@qq.com'
    auth_password: 'yanyuming123'
    auth_identity: 'server-lion@qq.com'
    require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']