global:
  scrape_interval: 15s  # 每 15 秒抓取一次指标

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - nginx:9095
    scheme: http
    timeout: 10s

# 告警规则配置
rule_files:
  - "alerts.yml"

scrape_configs:
  # 抓取我们的应用程序指标
  - job_name: 'app'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # 抓取 Prometheus 自身的指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus1:9090', 'prometheus2:9090']

  # 抓取 Alertmanager 指标
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager1:9093', 'alertmanager2:9093']